### PR TITLE
Add tag prop to form

### PR DESCRIPTION
**Pull request by kaleb**
Here is an example:

    <table>
    <tbody>
      <my-component v-for="(detail, i) in details" :detail="detail" inline-template @change="changeDetail(detail, i)">
        <vue-form tag="tr" :state="formstate">
          <validate tag="td">
            <input type="text" name="name" required>
          </validate>
        </vue-form
      </my-component>
    </tbody>
    <table>

### CODE REVIEW

**Comment by fergaldoyle** [comment]
I'll merge this to allow customization of `vue-form` tag (although it makes for it to be a `<form>` since it binds to the submit event).

Not sure about the use case above. Would it make more sense to have the table wrapped with `<vue-form>` then have dynamic `name` within the loop?

**Comment by kaleb** [comment]
I have a synthetic submit event in each row. Each row gets its own form
validation. I'll make a minimal example to demonstrate.

On Mon, Apr 3, 2017, 04:14 fergaldoyle <notifications@github.com> wrote:

I'll merge this to allow customization of vue-form tag (although it makes
for it to be a <form> since it binds to the submit event).

Not sure about the use case above. Would it make more sense to have the
table wrapped with <vue-form> then have dynamic name within the loop?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/fergaldoyle/vue-form/pull/45#issuecomment-291076655>,
or mute the thread

**Comment by kaleb** [comment]
Right now, I use code like this:

    const VueForm = require('vue-form');
    const VueFormComponent = VueForm.mixin.components[VueForm.config.formComponent];
    const MyComponent = {
        mixin: [VueForm],
        props: ['item'],
        data() {
            return {
                state: {},
            };
        },
        components: {
            VueForm: {
                mixin: [VueFormComponent],
                render(h) {
                    var vnode = VueFormComponent.render.call(this, h);
                    vnode.tag = 'tr';
                    return vnode;
                },
            },
        },
    },

Perhaps instead if you prefer, I could document this approach?

**Comment by kaleb** [comment]
I could use a parent form as you suggest and create names based on the index:

    <validaor v-for="(item, i) in items">
        <input :name="`item${i}`">
    </validator>

But, it would be nice if the behavior was more like how Vue treats refs and turn it into an array:

    <validaor v-for="(item, i) in items">
        <input name="item">
    </validator>

And then one could access `formstate.item[index].$error`

https://github.com/fergaldoyle/vue-form/blob/master/src/components/vue-form.js#L51

https://github.com/vuejs/vue/blob/e7a2510e631bd25f46b4e1125b83a9236a50ff1d/src/core/vdom/modules/ref.js#L34

I have not fully read all of the vue-form code yet to determine how difficult this would be to implement.

**Comment by kaleb** [comment]
Fixed in v4

**Pull request closed without merging**
